name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff src/
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src/orders_converter --cov-report=xml
      - name: Check coverage >= 90%
        run: |
          pip install coverage
          coverage report --fail-under=90
      # Add snapshot diff check here if using snapshot testing 